export enum TypeKeys {
  REPORT_ERROR = "REPORT_ERROR",
  LOGIN = "LOGIN",
  LOG_OUT = "LOG_OUT",
  SYNC_FAILED = "SYNC_FAILED",
  PUSH_TOKEN_FAILED = "PUSH_TOKEN_FAILED",
  LOG_OUT_FULFILLED = "LOG_OUT_FULFILLED",
  SOCIAL_LOGIN = 'SOCIAL_LOGIN_USER_FETCH',
  GOOGLE_LOGIN = 'GOOGLE_LOGIN',
  TWITTER_LOGIN = 'TWITTER_LOGIN',
  REGISTER = "REGISTER",
  UPDATE_PROFILE = "UPDATE_PROFILE",
  UPDATE_PROFILE_FULFILLED = "UPDATE_PROFILE_FULFILLED",
  REGISTER_SOCIAL = "REGISTER_SOCIAL",
  LOGIN_FULFILLED = "LOGIN_FULFILLED",
  POSTS = "POSTS",
  POSTS_FULFILLED = "POSTS_FULFILLED"
}