export enum TypeKeys {
  REPORT_ERROR = "REPORT_ERROR",
  LOGIN = "LOGIN",
  LOGIN_FULFILLED = "LOGIN_FULFILLED",
  POSTS = "POSTS",
  POSTS_FULFILLED = "POSTS_FULFILLED",
  SET_PINNED = "SET_PINNED",
  RESET = "RESET"
}